/* automatically generated by rust-bindgen 0.69.5 */

extern "C" {
    pub fn setup(
        base_uri: *const ::std::os::raw::c_char,
        inspect: ::std::os::raw::c_int,
        cb_ptr: *mut ::std::os::raw::c_void,
        done_cb: *mut ::std::os::raw::c_void,
        shot_cb: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn run();
}
extern "C" {
    pub fn navigate(url: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn screenshot();
}
extern "C" {
    pub fn set_title(title: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn set_size(
        pos_x: ::std::os::raw::c_int,
        pos_y: ::std::os::raw::c_int,
        size_x: ::std::os::raw::c_int,
        size_y: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn set_scale(layout_w: ::std::os::raw::c_int, layout_h: ::std::os::raw::c_int);
}
