name: Build Arexibo RPM

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  contents: write

jobs:
  build:
    uses: xiboplayer/.github/.github/workflows/build-rpm.yml@5c3b3699cd05c12bb3ec76e5d1d317d539dd69b4  # main
    with:
      package-name: arexibo
      rpm-spec: 'rpm/arexibo.spec'
      fedora-matrix: '["43", "44"]'
      arch-matrix: '["x86_64", "aarch64"]'
      source-tarball: 'full'
      gpg-sign: true
      default-version: '0.3.3'
      publish-to-repo: true
    secrets: inherit
